[build]
    command = "cd functions && yarn && cd .. && yarn build"
    publish = "public"
    functions = "functions"


[[redirects]]
  from = "/api/trending"
  to = "/.netlify/functions/get-trending"
  status = 200

[[redirects]]
  from = "/api/search"
  to = "/.netlify/functions/search"
  status = 200

# [dev]
# command = 'yarn develop'
# functionsPort = 34567
# port = 8000
# publish = 'public'
# targetPort = 8000